# Camera Settings
CAMERA_ID = 0
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480

# Hand Detection Settings
MAX_HANDS = 1
DETECTION_CONFIDENCE = 0.7
TRACKING_CONFIDENCE = 0.7

# Mouse Control Settings
SMOOTHING_FACTOR = 5
SCREEN_RESOLUTION = (1920, 1080)
